return function()
  vim.keymap.set('n', '<C-a>', function()
    require('harpoon.mark').add_file()
  end)
  vim.keymap.set('n', '<C-e>', function()
    require('harpoon.ui').toggle_quick_menu()
  end)
  vim.keymap.set('n', '<leader>7', function()
    require('harpoon.ui').nav_file(1)
  end)
  vim.keymap.set('n', '<leader>8', function()
    require('harpoon.ui').nav_file(2)
  end)
  vim.keymap.set('n', '<leader>9', function()
    require('harpoon.ui').nav_file(3)
  end)
  vim.keymap.set('n', '<leader>0', function()
    require('harpoon.ui').nav_file(4)
  end)
end
